spring:
  main:
    allow-bean-definition-overriding: true
  aop:
    auto: true
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://39.106.40.38:3306/online_end?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: Zjut123456
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.end.entity